stages:
- name: Build
  steps:
  - runScriptConfig:
      image: postman/newman
      shellScript: |
        run "https://www.getpostman.com/collections/8a0c9bc08f062d12dcda"
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-helloserver:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
notification: {}
